# 05. Export YOLOv8 Model to TensorFlow Lite

This notebook converts the trained DhakaRoadNet YOLOv8 model into TensorFlow Lite files for a native Android app built with Kotlin and XML. The goal is to create Android-ready model files, verify them on real/sample images, and save a clean export report for your portfolio and higher-study documentation.

## Step 1: Understand the export goal

- `.pt` is the PyTorch/Ultralytics training checkpoint. It is good for training and Python testing.
- `.tflite` is the TensorFlow Lite model format. It is suitable for Android on-device inference.
- FP32 TFLite is the safest baseline.
- FP16 TFLite is smaller and usually a good first Android option.
- INT8 TFLite is the most Edge AI focused option, but it must be checked carefully because accuracy can drop.

In [1]:
# Run this cell with RUN_INSTALLS = True only if export imports fail.
# After installation, restart(ctrl + shift + P) the notebook kernel and run from the top again.

RUN_INSTALLS = False # Change to True if imports fail due to missing packages.

if RUN_INSTALLS:
    import subprocess
    import sys

    core_packages = [
        "ultralytics",
        "torch",
        "onnx",
        "onnxruntime",
    ]
    
    optional_packages = [
        "onnxslim",
        "onnx2tf",
        "tf_keras",
        "sng4onnx",
        "onnx_graphsurgeon",
        "ai-edge-litert",
        "pandas",
        "tabulate",
        "packaging",
        "opencv-python",
        "pillow",
        "matplotlib",
    ]

    print("Installing core packages first...")
    for package in core_packages:
        try:
            print(f"  Installing {package}...")
            subprocess.check_call(
                [sys.executable, "-m", "pip", "install", "--upgrade", package],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.STDOUT
            )
            print(f"    ✓ {package}")
        except subprocess.CalledProcessError:
            print(f"    ✗ {package} failed. Continuing...")

    print("\\nInstalling optional packages...")
    for package in optional_packages:
        try:
            print(f"  Installing {package}...")
            subprocess.check_call(
                [sys.executable, "-m", "pip", "install", "--upgrade", package],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.STDOUT
            )
            print(f"    ✓ {package}")
        except subprocess.CalledProcessError:
            print(f"    ✗ {package} skipped (optional)")

    print("\\nInstalling TensorFlow required by Ultralytics TFLite export...")
    if sys.version_info >= (3, 13):
        print(f"    ✗ Current Python is {sys.version.split()[0]}.")
        print("    TensorFlow TFLite export is much more reliable with Python 3.11 or 3.12.")
        print("    Create a Python 3.11/3.12 environment for this export notebook.")
    else:
        try:
            subprocess.check_call(
                [sys.executable, "-m", "pip", "install", "--upgrade", "tensorflow>=2.19.0", "protobuf<6"],
            )
            print("    ✓ tensorflow>=2.19.0")
        except subprocess.CalledProcessError:
            print("    ✗ TensorFlow installation failed. TFLite export will be skipped until TensorFlow is installed.")

    print("\\nInstallation complete!")
else:
    print("Install step skipped. Set RUN_INSTALLS = True if export dependencies are missing.")

Install step skipped. Set RUN_INSTALLS = True if export dependencies are missing.

## Step 2: Import libraries

These imports are used for exporting, file management, simple prediction checks, and writing a readable export report.

In [2]:
from datetime import datetime
from pathlib import Path
import json
import shutil
import time

import cv2
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from PIL import Image
from ultralytics import YOLO

try:
    import tensorflow as tf
    TF_AVAILABLE = True
    TF_VERSION = tf.__version__
except Exception as tensorflow_error:
    tf = None
    TF_AVAILABLE = False
    TF_VERSION = None

print("Imports completed.")
print("Torch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("TensorFlow available:", TF_AVAILABLE)
print("TensorFlow version:", TF_VERSION)

Imports completed.
Torch: 2.12.0+cpu
CUDA available: False
TensorFlow available: True
TensorFlow version: 2.20.0

## Step 3: Configure paths and export settings

All important paths and settings are kept in one place. This makes the notebook easier to read and safer to modify later.

In [3]:
MODEL_RELATIVE_PATH = Path("model/checkpoints/yolov8n_dhakaroadnet_baseline/best.pt")
DATA_YAML_RELATIVE_PATH = Path("data/roboflow/data_yolov8.yaml")

IMAGE_SIZE = 640
BATCH_SIZE = 1
USE_NMS = True
EXPORT_DEVICE = "cpu"

EXPORT_DIR_RELATIVE_PATH = Path("model/exported/tflite")
REPORT_DIR_RELATIVE_PATH = Path("reports/tflite_export")

FP32_NAME = "dhakaroadnet_yolov8n_fp32.tflite"
FP16_NAME = "dhakaroadnet_yolov8n_fp16.tflite"
INT8_NAME = "dhakaroadnet_yolov8n_int8.tflite"

print("Export settings ready.")

Export settings ready.

## Step 4: Find the project root and check required files

This cell works whether Jupyter starts from the project root or from inside the `notebooks` folder.

In [4]:
def find_project_root(required_path: Path) -> Path:
    current = Path.cwd().resolve()
    for candidate in [current, *current.parents]:
        if (candidate / required_path).exists():
            return candidate
    raise FileNotFoundError(f"Could not find {required_path}. Check the project folder.")


PROJECT_ROOT = find_project_root(MODEL_RELATIVE_PATH)
MODEL_PATH = PROJECT_ROOT / MODEL_RELATIVE_PATH
DATA_YAML_PATH = PROJECT_ROOT / DATA_YAML_RELATIVE_PATH
EXPORT_DIR = PROJECT_ROOT / EXPORT_DIR_RELATIVE_PATH
REPORT_DIR = PROJECT_ROOT / REPORT_DIR_RELATIVE_PATH
PREDICTION_DIR = REPORT_DIR / "predictions"

EXPORT_DIR.mkdir(parents=True, exist_ok=True)
REPORT_DIR.mkdir(parents=True, exist_ok=True)
PREDICTION_DIR.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("Model exists:", MODEL_PATH.exists(), MODEL_PATH)
print("Dataset YAML exists:", DATA_YAML_PATH.exists(), DATA_YAML_PATH)
print("Export directory:", EXPORT_DIR)
print("Report directory:", REPORT_DIR)

Project root: C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI
Model exists: True C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\checkpoints\yolov8n_dhakaroadnet_baseline\best.pt
Dataset YAML exists: True C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\data\roboflow\data_yolov8.yaml
Export directory: C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\exported\tflite
Report directory: C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\reports\tflite_export

## Step 5: Check export dependencies

If any required package is missing, go back to the first code cell, set `RUN_INSTALLS = True`, run it, and restart the kernel.

In [5]:
import importlib.util
import sys
from importlib.metadata import PackageNotFoundError, version
from packaging.version import Version
import sys

required_packages = {
    "ultralytics": None,
    "torch": None,
    "tensorflow": "2.19.0",
    "onnx": None,
    "onnxruntime": None,
    "onnxslim": None,
    "onnx2tf": None,
    "tf_keras": None,
}

dependency_rows = []
for package_name, minimum_version in required_packages.items():
    available = importlib.util.find_spec(package_name) is not None
    installed_version = None
    version_ok = available

    if available:
        try:
            installed_version = version(package_name)
        except PackageNotFoundError:
            installed_version = "importable"

    if available and minimum_version and installed_version not in (None, "importable"):
        version_ok = Version(installed_version) >= Version(minimum_version)

    dependency_rows.append(
        {
            "package": package_name,
            "available": available,
            "version": installed_version,
            "minimum_version": minimum_version,
            "ready": version_ok,
        }
    )

dependency_table = pd.DataFrame(dependency_rows)
python_version = sys.version.split()[0]
python_ok_for_tensorflow = sys.version_info < (3, 13)

print("Python version:", python_version)
if not python_ok_for_tensorflow:
    print("This Python version is too new for reliable TensorFlow/TFLite export.")
    print("Use Python 3.11 or 3.12 for this notebook, then install tensorflow>=2.19.0.")

if not bool(dependency_table.loc[dependency_table["package"] == "tensorflow", "ready"].iloc[0]):
    print("TensorFlow is missing or too old for TFLite export.")
    print("Set RUN_INSTALLS = True in the first code cell, run it, then restart the kernel.")

dependency_table

Python version: 3.12.10

       package  available version minimum_version  ready
0  ultralytics       True  8.4.64             NaN   True
1        torch       True  2.12.0             NaN   True
2   tensorflow       True  2.20.0          2.19.0   True
3         onnx       True  1.20.1             NaN   True
4  onnxruntime       True  1.24.3             NaN   True
5     onnxslim       True  0.1.94             NaN   True
6      onnx2tf       True   2.4.1             NaN   True
7     tf_keras       True  2.20.1             NaN   True

## Step 6: Load the trained YOLOv8 model

This is the same final `best.pt` model used in evaluation and Gradio testing.

In [6]:
model = YOLO(str(MODEL_PATH))
class_names = model.names

print("Model loaded:", MODEL_PATH.name)
print("Number of classes:", len(class_names))
print(class_names)

Model loaded: best.pt
Number of classes: 24
{0: 'Auto rickshaw', 1: 'Bicycle', 2: 'Bus', 3: 'Car', 4: 'Dog', 5: 'Garbage van', 6: 'Human', 7: 'Leguna', 8: 'Manhole', 9: 'Micro Bus', 10: 'Mini truck', 11: 'Minivan', 12: 'Motorbike', 13: 'Pickup truck', 14: 'Police car', 15: 'Pothole', 16: 'Rickshaw', 17: 'Road barrier', 18: 'SUV', 19: 'Speed Breaker', 20: 'Three wheelers -CNG-', 21: 'Truck', 22: 'Van', 23: 'Zebra Crossing'}

## Step 7: Save Android labels

The Android app needs the same class names as the model. This creates a simple `labels.txt` file with one class per line.

In [7]:
labels_path = EXPORT_DIR / "labels.txt"
ordered_labels = [class_names[index] for index in sorted(class_names)]
labels_path.write_text("\n".join(ordered_labels), encoding="utf-8")

print("Saved labels:", labels_path)
print("First labels:", ordered_labels[:5])

Saved labels: C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\exported\tflite\labels.txt
First labels: ['Auto rickshaw', 'Bicycle', 'Bus', 'Car', 'Dog']

## Step 8: Create small helper functions

These helpers keep the export cells short. Each export will copy the generated `.tflite` file into a clean final filename.

In [8]:
from packaging.version import Version

export_records = []


def file_size_mb(path: Path) -> float:
    return round(path.stat().st_size / (1024 * 1024), 2)


def find_new_tflite_file(before_files, started_at):
    after_files = set(PROJECT_ROOT.rglob("*.tflite"))
    new_files = list(after_files - before_files)

    if not new_files:
        new_files = [p for p in after_files if p.stat().st_mtime >= started_at]

    if not new_files:
        raise FileNotFoundError("Export finished, but no new .tflite file was found.")

    return max(new_files, key=lambda p: p.stat().st_mtime)


def tensorflow_is_ready():
    if sys.version_info >= (3, 13):
        return False, f"Current Python is {sys.version.split()[0]}; use Python 3.11 or 3.12 for TensorFlow/TFLite export."
    if not TF_AVAILABLE or TF_VERSION is None:
        return False, "TensorFlow is not installed."
    if Version(TF_VERSION) < Version("2.19.0"):
        return False, f"TensorFlow {TF_VERSION} is installed, but Ultralytics requires tensorflow>=2.19.0."
    return True, f"TensorFlow {TF_VERSION} is ready."


def export_tflite_candidate(name, final_file_name, half=False, int8=False):
    print(f"Starting {name} export...")
    before_files = set(PROJECT_ROOT.rglob("*.tflite"))
    started_at = time.time()

    tf_ready, tf_message = tensorflow_is_ready()
    if not tf_ready:
        record = {
            "name": name,
            "status": "skipped",
            "path": "",
            "size_mb": None,
            "half": half,
            "int8": int8,
            "nms": USE_NMS,
            "imgsz": IMAGE_SIZE,
            "raw_export_result": "",
            "error": tf_message + " Set RUN_INSTALLS = True, run the first code cell, restart the kernel, then export again.",
        }
        print(f"Skipped {name}: {record['error']}")
        export_records.append(record)
        return record

    export_kwargs = {
        "format": "tflite",
        "imgsz": IMAGE_SIZE,
        "batch": BATCH_SIZE,
        "nms": USE_NMS,
        "device": EXPORT_DEVICE,
        "half": half,
        "int8": int8,
    }

    if int8:
        export_kwargs["data"] = str(DATA_YAML_PATH)

    try:
        raw_export_result = model.export(**export_kwargs)
        source_file = find_new_tflite_file(before_files, started_at)
        final_path = EXPORT_DIR / final_file_name
        shutil.copy2(source_file, final_path)

        record = {
            "name": name,
            "status": "success",
            "path": str(final_path),
            "size_mb": file_size_mb(final_path),
            "half": half,
            "int8": int8,
            "nms": USE_NMS,
            "imgsz": IMAGE_SIZE,
            "raw_export_result": str(raw_export_result),
            "error": "",
        }
        print(f"Finished {name}: {final_path} ({record['size_mb']} MB)")

    except Exception as exc:
        record = {
            "name": name,
            "status": "failed",
            "path": "",
            "size_mb": None,
            "half": half,
            "int8": int8,
            "nms": USE_NMS,
            "imgsz": IMAGE_SIZE,
            "raw_export_result": "",
            "error": str(exc),
        }
        print(f"{name} export failed:", exc)

    export_records.append(record)
    return record

## Step 9: Export FP32 TFLite

FP32 is the safest export. Use this first to confirm the conversion pipeline works.

In [9]:
fp32_record = export_tflite_candidate(
    name="FP32 TFLite",
    final_file_name=FP32_NAME,
    half=False,
    int8=False,
)
fp32_record

Starting FP32 TFLite export...
Ultralytics 8.4.64  Python-3.12.10 torch-2.12.0+cpu CPU (AMD Ryzen 3 3100 4-Core Processor)
Model summary (fused): 73 layers, 3,010,328 parameters, 0 gradients, 8.1 GFLOPs

PyTorch: starting from 'C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\checkpoints\yolov8n_dhakaroadnet_baseline\best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 6) (6.0 MB)

ONNX: starting export with onnx 1.20.1 opset 20...
ONNX: slimming with onnxslim 0.1.94...
ONNX: export success  2.1s, saved as 'C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\checkpoints\yolov8n_dhakaroadnet_baseline\best.onnx' (11.8 MB)
requirements: Ultralytics requirement ['onnx2tf>=1.26.3,<1.29.0'] not found, attempting AutoUpdate...
Collecting onnx2tf<1.29.0,>=1.26.3
  Downloading onnx2tf-1.28.8-py3-none-any.whl.metadata (152 kB)
Downloading onnx2tf-1.28.8-py3-none-any.whl (469 kB)
Installing collected packages: onnx2tf
  Attempting uninstall: onnx2tf
    Found existing installation: onnx2tf 2.4.1
    Uninstalling onnx2tf-2.4.1:
      Successfully uninstalled onnx2tf-2.4.1
Successfully installed onnx2tf-1.28.8

requirements: AutoUpdate success  6.9s
WARNING requirements: Restart runtime or rerun command for updates to take effect

requirements: Ultralytics requirement ['tf_keras<=2.19.0'] not found, attempting AutoUpdate...
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting tf_keras<=2.19.0
  Downloading tf_keras-2.19.0-py3-none-any.whl.metadata (1.8 kB)
Collecting tensorflow<2.20,>=2.19 (from tf_keras<=2.19.0)
  Downloading tensorflow-2.19.1-cp312-cp312-win_amd64.whl.metadata (4.1 kB)
Requirement already satisfied: absl-py>=1.0.0 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (3.4.0)
Requirement already satisfied: packaging in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (26.2)
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 (from tensorflow<2.20,>=2.19->tf_keras<=2.19.0)
  Downloading protobuf-5.29.6-cp310-abi3-win_amd64.whl.metadata (592 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (2.34.2)
Requirement already satisfied: setuptools in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (81.0.0)
Requirement already satisfied: six>=1.12.0 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (2.2.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (1.81.0)
Collecting tensorboard~=2.19.0 (from tensorflow<2.20,>=2.19->tf_keras<=2.19.0)
  Downloading tensorboard-2.19.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: keras>=3.5.0 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (3.14.1)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (1.26.4)
Requirement already satisfied: h5py>=3.11.0 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (3.16.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (2026.5.20)
Requirement already satisfied: markdown>=2.6.8 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (3.1.8)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from astunparse>=1.6.0->tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (0.47.0)
Requirement already satisfied: rich in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from keras>=3.5.0->tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (15.0.0)
Requirement already satisfied: namex in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from keras>=3.5.0->tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (0.1.0)
Requirement already satisfied: optree in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from keras>=3.5.0->tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (0.19.1)
Requirement already satisfied: markupsafe>=2.1.1 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from rich->keras>=3.5.0->tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from rich->keras>=3.5.0->tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\.venv-tflite\Lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow<2.20,>=2.19->tf_keras<=2.19.0) (0.1.2)
Downloading tf_keras-2.19.0-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 10.5 MB/s  0:00:00
Downloading tensorflow-2.19.1-cp312-cp312-win_amd64.whl (376.0 MB)
   ---------------------------------------- 0.0/376.0 MB ? eta -:--:--
   ---------------------------------------- 0.5/376.0 MB 8.2 MB/s eta 0:00:46
   ---------------------------------------- 0.8/376.0 MB 1.4 MB/s eta 0:04:29
   ---------------------------------------- 1.0/376.0 MB 1.4 MB/s eta 0:04:37
   ---------------------------------------- 2.1/376.0 MB 2.3 MB/s eta 0:02:40
   ---------------------------------------- 3.7/376.0 MB 3.6 MB/s eta 0:01:45
   ---------------------------------------- 3.7/376.0 MB 3.6 MB/s eta 0:01:45
   ---------------------------------------- 3.9/376.0 MB 2.6 MB/s eta 0:02:22
    --------------------------------------- 4.7/376.0 MB 2.8 MB/s eta 0:02:15
    --------------------------------------- 6.6/376.0 MB 3.5 MB/s eta 0:01:46
    --------------------------------------- 7.6/376.0 MB 3.7 MB/s eta 0:01:41
    --------------------------------------- 9.2/376.0 MB 4.0 MB/s eta 0:01:32
   - -------------------------------------- 10.0/376.0 MB 4.1 MB/s eta 0:01:30
   - -------------------------------------- 12.1/376.0 MB 4.5 MB/s eta 0:01:22
   - -------------------------------------- 13.4/376.0 MB 4.6 MB/s eta 0:01:19
   - -------------------------------------- 14.9/376.0 MB 4.8 MB/s eta 0:01:15
   - -------------------------------------- 16.3/376.0 MB 4.9 MB/s eta 0:01:13
   - -------------------------------------- 17.8/376.0 MB 5.1 MB/s eta 0:01:11
   -- ------------------------------------- 19.4/376.0 MB 5.2 MB/s eta 0:01:09
   -- ------------------------------------- 21.0/376.0 MB 5.3 MB/s eta 0:01:07
   -- ------------------------------------- 22.5/376.0 MB 5.5 MB/s eta 0:01:05
   -- ------------------------------------- 24.1/376.0 MB 5.6 MB/s eta 0:01:04
   -- ------------------------------------- 25.2/376.0 MB 5.6 MB/s eta 0:01:04
   -- ------------------------------------- 26.2/376.0 MB 5.6 MB/s eta 0:01:03
   -- ------------------------------------- 27.5/376.0 MB 5.6 MB/s eta 0:01:03
   --- ------------------------------------ 28.6/376.0 MB 5.6 MB/s eta 0:01:03
   --- ------------------------------------ 29.9/376.0 MB 5.6 MB/s eta 0:01:02
   --- ------------------------------------ 31.2/376.0 MB 5.6 MB/s eta 0:01:02
   --- ------------------------------------ 32.5/376.0 MB 5.6 MB/s eta 0:01:01
   --- ------------------------------------ 33.8/376.0 MB 5.7 MB/s eta 0:01:01
   --- ------------------------------------ 35.1/376.0 MB 5.7 MB/s eta 0:01:00
   --- ------------------------------------ 36.4/376.0 MB 5.7 MB/s eta 0:01:00
   ---- ----------------------------------- 37.7/376.0 MB 5.7 MB/s eta 0:01:00
   ---- ----------------------------------- 39.1/376.0 MB 5.7 MB/s eta 0:00:59
   ---- ----------------------------------- 40.4/376.0 MB 5.8 MB/s eta 0:00:59
   ---- ----------------------------------- 41.7/376.0 MB 5.8 MB/s eta 0:00:58
   ---- ----------------------------------- 43.3/376.0 MB 5.8 MB/s eta 0:00:58
   ---- ----------------------------------- 44.6/376.0 MB 5.8 MB/s eta 0:00:57
   ---- ----------------------------------- 45.9/376.0 MB 5.9 MB/s eta 0:00:57
   ----- ---------------------------------- 47.2/376.0 MB 5.9 MB/s eta 0:00:56
   ----- ---------------------------------- 48.5/376.0 MB 5.9 MB/s eta 0:00:56
   ----- ---------------------------------- 49.8/376.0 MB 5.9 MB/s eta 0:00:56
   ----- ---------------------------------- 51.4/376.0 MB 5.9 MB/s eta 0:00:55
   ----- ---------------------------------- 52.7/376.0 MB 5.9 MB/s eta 0:00:55
   ----- ---------------------------------- 54.3/376.0 MB 6.0 MB/s eta 0:00:54
   ----- ---------------------------------- 55.6/376.0 MB 6.0 MB/s eta 0:00:54
   ------ --------------------------------- 57.1/376.0 MB 6.0 MB/s eta 0:00:53
   ------ --------------------------------- 58.5/376.0 MB 6.0 MB/s eta 0:00:53
   ------ --------------------------------- 60.0/376.0 MB 6.1 MB/s eta 0:00:53
   ------ --------------------------------- 61.6/376.0 MB 6.1 MB/s eta 0:00:52
   ------ --------------------------------- 62.9/376.0 MB 6.1 MB/s eta 0:00:52
   ------ --------------------------------- 64.5/376.0 MB 6.1 MB/s eta 0:00:51
   ------- -------------------------------- 66.1/376.0 MB 6.2 MB/s eta 0:00:51
   ------- -------------------------------- 67.6/376.0 MB 6.2 MB/s eta 0:00:50
   ------- -------------------------------- 69.2/376.0 MB 6.2 MB/s eta 0:00:50
   ------- -------------------------------- 70.8/376.0 MB 6.3 MB/s eta 0:00:49
   ------- -------------------------------- 72.4/376.0 MB 6.3 MB/s eta 0:00:49
   ------- -------------------------------- 73.9/376.0 MB 6.3 MB/s eta 0:00:48
   -------- ------------------------------- 75.5/376.0 MB 6.3 MB/s eta 0:00:48
   -------- ------------------------------- 76.8/376.0 MB 6.4 MB/s eta 0:00:48
   -------- ------------------------------- 78.4/376.0 MB 6.3 MB/s eta 0:00:47
   -------- ------------------------------- 79.4/376.0 MB 6.3 MB/s eta 0:00:47
   -------- ------------------------------- 80.7/376.0 MB 6.3 MB/s eta 0:00:47
   -------- ------------------------------- 82.1/376.0 MB 6.3 MB/s eta 0:00:47
   -------- ------------------------------- 83.4/376.0 MB 6.3 MB/s eta 0:00:47
   --------- ------------------------------ 84.7/376.0 MB 6.3 MB/s eta 0:00:46
   --------- ------------------------------ 86.2/376.0 MB 6.3 MB/s eta 0:00:46
   --------- ------------------------------ 87.6/376.0 MB 6.3 MB/s eta 0:00:46
   --------- ------------------------------ 89.1/376.0 MB 6.4 MB/s eta 0:00:46
   --------- ------------------------------ 90.4/376.0 MB 6.4 MB/s eta 0:00:45
   --------- ------------------------------ 92.0/376.0 MB 6.4 MB/s eta 0:00:45
   --------- ------------------------------ 93.6/376.0 MB 6.4 MB/s eta 0:00:45
   ---------- ----------------------------- 95.2/376.0 MB 6.4 MB/s eta 0:00:44
   ---------- ----------------------------- 96.7/376.0 MB 6.4 MB/s eta 0:00:44
   ---------- ----------------------------- 98.3/376.0 MB 6.4 MB/s eta 0:00:44
   ---------- ----------------------------- 99.9/376.0 MB 6.5 MB/s eta 0:00:43
   ---------- ----------------------------- 101.4/376.0 MB 6.5 MB/s eta 0:00:43
   ---------- ----------------------------- 103.0/376.0 MB 6.5 MB/s eta 0:00:42
   ----------- ---------------------------- 104.6/376.0 MB 6.5 MB/s eta 0:00:42
   ----------- ---------------------------- 105.9/376.0 MB 6.5 MB/s eta 0:00:42
   ----------- ---------------------------- 107.2/376.0 MB 6.5 MB/s eta 0:00:42
   ----------- ---------------------------- 108.5/376.0 MB 6.5 MB/s eta 0:00:42
   ----------- ---------------------------- 109.8/376.0 MB 6.5 MB/s eta 0:00:41
   ----------- ---------------------------- 110.9/376.0 MB 6.5 MB/s eta 0:00:41
   ----------- ---------------------------- 112.2/376.0 MB 6.5 MB/s eta 0:00:41
   ------------ --------------------------- 113.5/376.0 MB 6.5 MB/s eta 0:00:41
   ------------ --------------------------- 114.8/376.0 MB 6.5 MB/s eta 0:00:41
   ------------ --------------------------- 116.1/376.0 MB 6.5 MB/s eta 0:00:41
   ------------ --------------------------- 117.4/376.0 MB 6.5 MB/s eta 0:00:40
   ------------ --------------------------- 118.8/376.0 MB 6.5 MB/s eta 0:00:40
   ------------ --------------------------- 120.1/376.0 MB 6.5 MB/s eta 0:00:40
   ------------ --------------------------- 121.4/376.0 MB 6.5 MB/s eta 0:00:40
   ------------- -------------------------- 122.9/376.0 MB 6.5 MB/s eta 0:00:40
   ------------- -------------------------- 124.3/376.0 MB 6.5 MB/s eta 0:00:39
   ------------- -------------------------- 125.6/376.0 MB 6.5 MB/s eta 0:00:39
   ------------- -------------------------- 126.9/376.0 MB 6.5 MB/s eta 0:00:39
   ------------- -------------------------- 128.5/376.0 MB 6.5 MB/s eta 0:00:39
   ------------- -------------------------- 129.8/376.0 MB 6.5 MB/s eta 0:00:38
   ------------- -------------------------- 131.1/376.0 MB 6.5 MB/s eta 0:00:38
   -------------- ------------------------- 132.6/376.0 MB 6.5 MB/s eta 0:00:38
   -------------- ------------------------- 134.0/376.0 MB 6.5 MB/s eta 0:00:38
   -------------- ------------------------- 135.5/376.0 MB 6.5 MB/s eta 0:00:37
   -------------- ------------------------- 136.8/376.0 MB 6.5 MB/s eta 0:00:37
   -------------- ------------------------- 138.1/376.0 MB 6.5 MB/s eta 0:00:37
   -------------- ------------------------- 139.7/376.0 MB 6.5 MB/s eta 0:00:37
   --------------- ------------------------ 141.3/376.0 MB 6.5 MB/s eta 0:00:36
   --------------- ------------------------ 142.9/376.0 MB 6.5 MB/s eta 0:00:36
   --------------- ------------------------ 144.2/376.0 MB 6.5 MB/s eta 0:00:36
   --------------- ------------------------ 145.8/376.0 MB 6.6 MB/s eta 0:00:36
   --------------- ------------------------ 147.1/376.0 MB 6.6 MB/s eta 0:00:35
   --------------- ------------------------ 148.4/376.0 MB 6.6 MB/s eta 0:00:35
   --------------- ------------------------ 149.2/376.0 MB 6.5 MB/s eta 0:00:35
   --------------- ------------------------ 149.9/376.0 MB 6.5 MB/s eta 0:00:35
   --------------- ------------------------ 150.2/376.0 MB 6.5 MB/s eta 0:00:35
   ---------------- ----------------------- 150.5/376.0 MB 6.5 MB/s eta 0:00:35
   ---------------- ----------------------- 150.7/376.0 MB 6.4 MB/s eta 0:00:36
   ---------------- ----------------------- 151.0/376.0 MB 6.4 MB/s eta 0:00:36
   ---------------- ----------------------- 151.3/376.0 MB 6.3 MB/s eta 0:00:36
   ---------------- ----------------------- 151.3/376.0 MB 6.3 MB/s eta 0:00:36
   ---------------- ----------------------- 151.5/376.0 MB 6.2 MB/s eta 0:00:37
   ---------------- ----------------------- 151.5/376.0 MB 6.2 MB/s eta 0:00:37
   ---------------- ----------------------- 151.5/376.0 MB 6.2 MB/s eta 0:00:37
   ---------------- ----------------------- 151.5/376.0 MB 6.2 MB/s eta 0:00:37
   ---------------- ----------------------- 151.8/376.0 MB 6.0 MB/s eta 0:00:38
   ---------------- ----------------------- 151.8/376.0 MB 6.0 MB/s eta 0:00:38
   ---------------- ----------------------- 151.8/376.0 MB 6.0 MB/s eta 0:00:38
   ---------------- ----------------------- 151.8/376.0 MB 6.0 MB/s eta 0:00:38
   ---------------- ----------------------- 152.0/376.0 MB 5.8 MB/s eta 0:00:39
   ---------------- ----------------------- 152.0/376.0 MB 5.8 MB/s eta 0:00:39
   ---------------- ----------------------- 152.0/376.0 MB 5.8 MB/s eta 0:00:39
   ---------------- ----------------------- 152.0/376.0 MB 5.8 MB/s eta 0:00:39
   ---------------- ----------------------- 152.3/376.0 MB 5.7 MB/s eta 0:00:40
   ---------------- ----------------------- 152.3/376.0 MB 5.7 MB/s eta 0:00:40
   ---------------- ----------------------- 152.3/376.0 MB 5.7 MB/s eta 0:00:40

{'name': 'FP32 TFLite',
 'status': 'success',
 'path': 'C:\\Users\\USER\\Desktop\\ML\\WorkSpace\\DhakaRoadNet-EdgeAI\\model\\exported\\tflite\\dhakaroadnet_yolov8n_fp32.tflite',
 'size_mb': 11.78,
 'half': False,
 'int8': False,
 'nms': True,
 'imgsz': 640,
 'raw_export_result': 'C:\\Users\\USER\\Desktop\\ML\\WorkSpace\\DhakaRoadNet-EdgeAI\\model\\checkpoints\\yolov8n_dhakaroadnet_baseline\\best_saved_model\\best_float32.tflite',
 'error': ''}

## Step 10: Export FP16 TFLite

FP16 is usually the best first Android candidate because it is smaller than FP32 and often keeps similar accuracy.

In [10]:
fp16_record = export_tflite_candidate(
    name="FP16 TFLite",
    final_file_name=FP16_NAME,
    half=True,
    int8=False,
)
fp16_record

Starting FP16 TFLite export...
Ultralytics 8.4.64  Python-3.12.10 torch-2.12.0+cpu CPU (AMD Ryzen 3 3100 4-Core Processor)
Model summary (fused): 73 layers, 3,010,328 parameters, 0 gradients, 8.1 GFLOPs

PyTorch: starting from 'C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\checkpoints\yolov8n_dhakaroadnet_baseline\best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 6) (6.0 MB)

ONNX: starting export with onnx 1.20.1 opset 20...
ONNX: slimming with onnxslim 0.1.94...
ONNX: export success  1.9s, saved as 'C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\checkpoints\yolov8n_dhakaroadnet_baseline\best.onnx' (11.8 MB)

TensorFlow SavedModel: starting export with tensorflow 2.20.0...
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.28.8...
Saved artifact at 'C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\checkpoints\yolov8n_dhakaroadnet_baseline\best_saved_model'. The following endpoints are available:

* Endpoint 'serving_default'
  inputs_0 (POSITIONAL_ONLY): TensorSpec(shape=(1, 640, 640, 3), dtype=tf.float32, name='images')
Output Type:
  TensorSpec(shape=(1, 300, 6), dtype=tf.float32, name=None)
Captures:
  1696939867792: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  1696939867216: TensorSpec(shape=(3, 3, 3, 16), dtype=tf.float32, name=None)
  1696939861072: TensorSpec(shape=(16,), dtype=tf.float32, name=None)
  1696939860304: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  1696939867984: TensorSpec(shape=(3, 3, 16, 32), dtype=tf.float32, name=None)
  1696939862032: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  1696939863760: TensorSpec(shape=(1, 1, 32, 32), dtype=tf.float32, name=None)
  1696939864336: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  1696939866064: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696939860112: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696939859536: TensorSpec(shape=(3, 3, 16, 16), dtype=tf.float32, name=None)
  1696939858000: TensorSpec(shape=(16,), dtype=tf.float32, name=None)
  1696939866256: TensorSpec(shape=(3, 3, 16, 16), dtype=tf.float32, name=None)
  1696939863184: TensorSpec(shape=(16,), dtype=tf.float32, name=None)
  1696939863568: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696939862992: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697124107664: TensorSpec(shape=(1, 1, 48, 32), dtype=tf.float32, name=None)
  1697124107472: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  1697124108048: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  1697124106896: TensorSpec(shape=(3, 3, 32, 64), dtype=tf.float32, name=None)
  1697124107856: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697124108240: TensorSpec(shape=(1, 1, 64, 64), dtype=tf.float32, name=None)
  1697124108432: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697124109008: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697124108816: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697124110928: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  1697124111120: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  1697124108624: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  1697124107088: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  1697124110352: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  1697124111312: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  1697124109968: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  1697124111696: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  1697124109200: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697124109392: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697124112080: TensorSpec(shape=(1, 1, 128, 64), dtype=tf.float32, name=None)
  1697124111504: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697124112272: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  1697124110544: TensorSpec(shape=(3, 3, 64, 128), dtype=tf.float32, name=None)
  1697124111888: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1697124112656: TensorSpec(shape=(1, 1, 128, 128), dtype=tf.float32, name=None)
  1697124112848: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1697124113424: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697124113232: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697124115344: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1697124115536: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697124113040: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1697124112464: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697124114768: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1697124115728: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697124114384: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1697124116112: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697124113616: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697124113808: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697124116496: TensorSpec(shape=(1, 1, 256, 128), dtype=tf.float32, name=None)
  1697124115920: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1697124116688: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  1697124114960: TensorSpec(shape=(3, 3, 128, 256), dtype=tf.float32, name=None)
  1697124116304: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  1697124117072: TensorSpec(shape=(1, 1, 256, 256), dtype=tf.float32, name=None)
  1697124117264: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  1697124117840: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697124117648: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697124119760: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  1697124119952: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1697124117456: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  1697124116880: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1697124118032: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697124118224: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697124120144: TensorSpec(shape=(1, 1, 384, 256), dtype=tf.float32, name=None)
  1697124118800: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  1697124119184: TensorSpec(shape=(1, 1, 256, 128), dtype=tf.float32, name=None)
  1697124120528: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1697124120720: TensorSpec(shape=(1, 1, 512, 256), dtype=tf.float32, name=None)
  1697124120336: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  1697124121296: TensorSpec(shape=(1, 1, 384, 128), dtype=tf.float32, name=None)
  1697124119376: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1697124121488: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697124122448: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697124121680: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1697124122256: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697124121104: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1697124120912: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697124121872: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697124122064: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697131169360: TensorSpec(shape=(1, 1, 192, 128), dtype=tf.float32, name=None)
  1697131169168: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1697131168592: TensorSpec(shape=(1, 1, 192, 64), dtype=tf.float32, name=None)
  1697131168400: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697131169936: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697131169744: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697131171856: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  1697131172048: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  1697131169552: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  1697131168976: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  1697131170128: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697131170320: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697131172432: TensorSpec(shape=(1, 1, 96, 64), dtype=tf.float32, name=None)
  1697131172240: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697131172624: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  1697131171280: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1697131170896: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697131174544: TensorSpec(shape=(1, 1, 192, 128), dtype=tf.float32, name=None)
  1697131173968: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1696789578960: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696789579152: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696789580880: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1696789580688: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696789581072: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1696789580304: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696789579728: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696789579536: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696939865488: TensorSpec(shape=(1, 1, 192, 128), dtype=tf.float32, name=None)
  1696939862224: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1696939867024: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  1696939865680: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  1696939857232: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1696939854928: TensorSpec(shape=(1, 1, 384, 256), dtype=tf.float32, name=None)
  1696939853776: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  1696939854160: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696939854352: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696939854736: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  1696939856272: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1696939857808: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  1696939859344: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1696939855504: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696939855888: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696939858768: TensorSpec(shape=(1, 1, 384, 256), dtype=tf.float32, name=None)
  1696939859920: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  1696939856848: TensorSpec(shape=(3, 3, 256, 64), dtype=tf.float32, name=None)
  1696939862608: TensorSpec(shape=(3, 3, 128, 64), dtype=tf.float32, name=None)
  1697131173008: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1696939853200: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696939860496: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697131172816: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696939859728: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1696939864528: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1697131173200: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1696939852048: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696939858384: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697131173584: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696939853392: TensorSpec(shape=(1, 1, 64, 64), dtype=tf.float32, name=None)
  1696939851856: TensorSpec(shape=(1, 1, 64, 64), dtype=tf.float32, name=None)
  1696789580496: TensorSpec(shape=(1, 1, 64, 64), dtype=tf.float32, name=None)
  1696939856464: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696939852624: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696789581456: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696939855696: TensorSpec(shape=(3, 3, 256, 64), dtype=tf.float32, name=None)
  1696939861264: TensorSpec(shape=(3, 3, 128, 64), dtype=tf.float32, name=None)
  1697131173392: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1696939859152: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696939864720: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697131171472: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696939857040: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1696939852816: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1697131174160: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1696939857424: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696939864144: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697131173776: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696939856080: TensorSpec(shape=(1, 1, 64, 24), dtype=tf.float32, name=None)
  1696939853968: TensorSpec(shape=(1, 1, 64, 24), dtype=tf.float32, name=None)
  1696789580112: TensorSpec(shape=(1, 1, 64, 24), dtype=tf.float32, name=None)
  1696939858960: TensorSpec(shape=(1, 1, 16, 1), dtype=tf.float32, name=None)
  1696939857616: TensorSpec(shape=(24,), dtype=tf.float32, name=None)
  1696939854544: TensorSpec(shape=(24,), dtype=tf.float32, name=None)
  1696789579344: TensorSpec(shape=(24,), dtype=tf.float32, name=None)
  1696795658960: TensorSpec(shape=(3,), dtype=tf.int64, name=None)
  1696795657808: TensorSpec(shape=(3,), dtype=tf.int64, name=None)
  1696795661456: TensorSpec(shape=(3,), dtype=tf.int64, name=None)
  1696795658576: TensorSpec(shape=(3,), dtype=tf.int64, name=None)
  1696795662992: TensorSpec(shape=(1, 2, 8400), dtype=tf.float32, name=None)
  1696939852432: TensorSpec(shape=(1, 2, 8400), dtype=tf.float32, name=None)
  1696795664528: TensorSpec(shape=(3,), dtype=tf.int64, name=None)
  1696795663184: TensorSpec(shape=(3,), dtype=tf.int64, name=None)
  1696795660688: TensorSpec(shape=(3,), dtype=tf.int64, name=None)
  1696795659728: TensorSpec(shape=(3,), dtype=tf.int64, name=None)
  1696795669328: TensorSpec(shape=(1500, 4), dtype=tf.int64, name=None)
  1696795669136: TensorSpec(shape=(2,), dtype=tf.int64, name=None)
  1696795661840: TensorSpec(shape=(2,), dtype=tf.int64, name=None)
  1696795670288: TensorSpec(shape=(), dtype=tf.int32, name=None)
  1696795671056: TensorSpec(shape=(), dtype=tf.int32, name=None)
  1696795668944: TensorSpec(shape=(1,), dtype=tf.bool, name=None)
  1696795667024: TensorSpec(shape=(1,), dtype=tf.int32, name=None)
  1696795670864: TensorSpec(shape=(), dtype=tf.int32, name=None)
  1696795666064: TensorSpec(shape=(), dtype=tf.int32, name=None)
  1696795669904: TensorSpec(shape=(), dtype=tf.int32, name=None)
  1696795670672: TensorSpec(shape=(), dtype=tf.float32, name=None)
  1696795666832: TensorSpec(shape=(), dtype=tf.float32, name=None)
  1696795664336: TensorSpec(shape=(3,), dtype=tf.int64, name=None)
  1696795665104: TensorSpec(shape=(3,), dtype=tf.int64, name=None)
  1696795671824: TensorSpec(shape=(2, 2), dtype=tf.int32, name=None)
  1696795670480: TensorSpec(shape=(), dtype=tf.int64, name=None)
  1696795670096: TensorSpec(shape=(), dtype=tf.int64, name=None)
  1696795668176: TensorSpec(shape=(1,), dtype=tf.int64, name=None)
  1696795668368: TensorSpec(shape=(1,), dtype=tf.int64, name=None)
  1696795667408: TensorSpec(shape=(1,), dtype=tf.int64, name=None)
  1696795661648: TensorSpec(shape=(), dtype=tf.int64, name=None)
  1696795671248: TensorSpec(shape=(1,), dtype=tf.int64, name=None)
  1696795662032: TensorSpec(shape=(1,), dtype=tf.int64, name=None)
  1696795664912: TensorSpec(shape=(1,), dtype=tf.int64, name=None)
  1696800556048: TensorSpec(shape=(1, 300, 6), dtype=tf.float32, name=None)
  1696800555280: TensorSpec(shape=(1, 1), dtype=tf.int64, name=None)
TensorFlow SavedModel: export success  15.1s, saved as 'C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\checkpoints\yolov8n_dhakaroadnet_baseline\best_saved_model' (29.7 MB)

TensorFlow Lite: starting export with tensorflow 2.20.0...
TensorFlow Lite: export success  0.0s, saved as 'C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\checkpoints\yolov8n_dhakaroadnet_baseline\best_saved_model\best_float16.tflite' (6.0 MB)

Export complete (15.4s)
Results saved to C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\checkpoints\yolov8n_dhakaroadnet_baseline\best_saved_model\best_float16.tflite
Predict:         yolo predict task=detect model=C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\checkpoints\yolov8n_dhakaroadnet_baseline\best_saved_model\best_float16.tflite imgsz=640 half
Validate:        yolo val task=detect model=C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\checkpoints\yolov8n_dhakaroadnet_baseline\best_saved_model\best_float16.tflite imgsz=640 data=C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\data\roboflow\data_yolov8.yaml half
Visualize:       https://netron.app
Finished FP16 TFLite: C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\exported\tflite\dhakaroadnet_yolov8n_fp16.tflite (11.79 MB)

{'name': 'FP16 TFLite',
 'status': 'success',
 'path': 'C:\\Users\\USER\\Desktop\\ML\\WorkSpace\\DhakaRoadNet-EdgeAI\\model\\exported\\tflite\\dhakaroadnet_yolov8n_fp16.tflite',
 'size_mb': 11.79,
 'half': True,
 'int8': False,
 'nms': True,
 'imgsz': 640,
 'raw_export_result': 'C:\\Users\\USER\\Desktop\\ML\\WorkSpace\\DhakaRoadNet-EdgeAI\\model\\checkpoints\\yolov8n_dhakaroadnet_baseline\\best_saved_model\\best_float16.tflite',
 'error': ''}

## Step 11: Export INT8 TFLite

INT8 is the strongest Edge AI option for size and speed. It uses your dataset YAML for calibration. If accuracy drops too much, use FP16 first in Android.

In [11]:
int8_record = export_tflite_candidate(
    name="INT8 TFLite",
    final_file_name=INT8_NAME,
    half=False,
    int8=True,
)
int8_record

Starting INT8 TFLite export...
Ultralytics 8.4.64  Python-3.12.10 torch-2.12.0+cpu CPU (AMD Ryzen 3 3100 4-Core Processor)
Model summary (fused): 73 layers, 3,010,328 parameters, 0 gradients, 8.1 GFLOPs

PyTorch: starting from 'C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\checkpoints\yolov8n_dhakaroadnet_baseline\best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 6) (6.0 MB)
TensorFlow SavedModel: collecting INT8 calibration images from 'data=C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\data\roboflow\data_yolov8.yaml'
val: Fast image access  (ping: 0.10.0 ms, read: 101.019.7 MB/s, size: 65.8 KB)
val: Scanning C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\data\roboflow\valid\labels.cache... 195 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 195/195  0.0s
WARNING TensorFlow SavedModel: >300 images recommended for INT8 calibration, found 195 images.

ONNX: starting export with onnx 1.20.1 opset 20...
ONNX: slimming with onnxslim 0.1.94...
ONNX: export success  2.7s, saved as 'C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\checkpoints\yolov8n_dhakaroadnet_baseline\best.onnx' (11.8 MB)

TensorFlow SavedModel: starting export with tensorflow 2.20.0...
TensorFlow SavedModel: starting TFLite export with onnx2tf 1.28.8...
Saved artifact at 'C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\checkpoints\yolov8n_dhakaroadnet_baseline\best_saved_model'. The following endpoints are available:

* Endpoint 'serving_default'
  inputs_0 (POSITIONAL_ONLY): TensorSpec(shape=(1, 640, 640, 3), dtype=tf.float32, name='images')
Output Type:
  TensorSpec(shape=(1, 300, 6), dtype=tf.float32, name=None)
Captures:
  1696789581072: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  1696789578960: TensorSpec(shape=(3, 3, 3, 16), dtype=tf.float32, name=None)
  1696789579536: TensorSpec(shape=(16,), dtype=tf.float32, name=None)
  1696789579728: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  1696800556048: TensorSpec(shape=(3, 3, 16, 32), dtype=tf.float32, name=None)
  1696789580496: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  1696789581456: TensorSpec(shape=(1, 1, 32, 32), dtype=tf.float32, name=None)
  1696789579344: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  1697131169168: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697131175888: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696789580688: TensorSpec(shape=(3, 3, 16, 16), dtype=tf.float32, name=None)
  1696789580304: TensorSpec(shape=(16,), dtype=tf.float32, name=None)
  1696789580112: TensorSpec(shape=(3, 3, 16, 16), dtype=tf.float32, name=None)
  1697131169744: TensorSpec(shape=(16,), dtype=tf.float32, name=None)
  1697131176464: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697131175312: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697131171856: TensorSpec(shape=(1, 1, 48, 32), dtype=tf.float32, name=None)
  1697131169936: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  1697131169552: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  1697131169360: TensorSpec(shape=(3, 3, 32, 64), dtype=tf.float32, name=None)
  1697131172048: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697131168976: TensorSpec(shape=(1, 1, 64, 64), dtype=tf.float32, name=None)
  1697131170128: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697131172240: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697131172432: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697131173392: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  1697131171472: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  1697131170320: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  1697131168592: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  1697131172816: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  1697131174160: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  1697131173968: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  1697131170704: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  1697131172624: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697131171280: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697131171088: TensorSpec(shape=(1, 1, 128, 64), dtype=tf.float32, name=None)
  1697131173776: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697131170512: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  1697131173200: TensorSpec(shape=(3, 3, 64, 128), dtype=tf.float32, name=None)
  1697131171664: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1697131167824: TensorSpec(shape=(1, 1, 128, 128), dtype=tf.float32, name=None)
  1697131168784: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1697131175120: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697131181264: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697131177616: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1697131183760: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697131168208: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1697131168016: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697131178384: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1697131175504: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697131183184: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1697131177424: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1697131178768: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697131181840: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697131180880: TensorSpec(shape=(1, 1, 256, 128), dtype=tf.float32, name=None)
  1697131183952: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1697131178000: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  1697131181456: TensorSpec(shape=(3, 3, 128, 256), dtype=tf.float32, name=None)
  1697131182032: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  1697131178192: TensorSpec(shape=(1, 1, 256, 256), dtype=tf.float32, name=None)
  1697131182416: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  1697131177232: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697131180112: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697131176656: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  1697131176272: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1697131180496: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  1697131179728: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1697131175696: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1697131174352: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696795658576: TensorSpec(shape=(1, 1, 384, 256), dtype=tf.float32, name=None)
  1696795661456: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  1696795659920: TensorSpec(shape=(1, 1, 256, 128), dtype=tf.float32, name=None)
  1696795664528: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1696795663184: TensorSpec(shape=(1, 1, 512, 256), dtype=tf.float32, name=None)
  1696795662992: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  1696795669328: TensorSpec(shape=(1, 1, 384, 128), dtype=tf.float32, name=None)
  1696795658960: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1696795661840: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696795669136: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696795664336: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1696795665104: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696795659728: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1696795660688: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696795670288: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696795671056: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696795670480: TensorSpec(shape=(1, 1, 192, 128), dtype=tf.float32, name=None)
  1696795671824: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1696795670672: TensorSpec(shape=(1, 1, 192, 64), dtype=tf.float32, name=None)
  1696795669904: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696795668368: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696795668176: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696795658768: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  1696795671440: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  1696795670096: TensorSpec(shape=(3, 3, 32, 32), dtype=tf.float32, name=None)
  1696795670864: TensorSpec(shape=(32,), dtype=tf.float32, name=None)
  1696795667408: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696795661648: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696795671632: TensorSpec(shape=(1, 1, 96, 64), dtype=tf.float32, name=None)
  1696795660496: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696795672016: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  1696795667792: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1696795664912: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696795666640: TensorSpec(shape=(1, 1, 192, 128), dtype=tf.float32, name=None)
  1696795667984: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1696795663760: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696795664720: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696795661264: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1696795662416: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696795665872: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1696795658384: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696795668560: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696795662224: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696795665488: TensorSpec(shape=(1, 1, 192, 128), dtype=tf.float32, name=None)
  1696795660304: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1696939861072: TensorSpec(shape=(4, 2), dtype=tf.int32, name=None)
  1696795659152: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  1696939867984: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1696939863568: TensorSpec(shape=(1, 1, 384, 256), dtype=tf.float32, name=None)
  1696939858000: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  1696939865680: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696939862224: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696939857232: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  1696939858768: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1696939859344: TensorSpec(shape=(3, 3, 128, 128), dtype=tf.float32, name=None)
  1696939853200: TensorSpec(shape=(128,), dtype=tf.float32, name=None)
  1696939853776: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696939854160: TensorSpec(shape=(4,), dtype=tf.int64, name=None)
  1696939859728: TensorSpec(shape=(1, 1, 384, 256), dtype=tf.float32, name=None)
  1696939860496: TensorSpec(shape=(256,), dtype=tf.float32, name=None)
  1696939856272: TensorSpec(shape=(3, 3, 256, 64), dtype=tf.float32, name=None)
  1696939862032: TensorSpec(shape=(3, 3, 128, 64), dtype=tf.float32, name=None)
  1696795672208: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1696939859920: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696939863760: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696795662800: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696939856848: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1696939864336: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1696795669520: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1696939852048: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696939860112: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696795668752: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696939853392: TensorSpec(shape=(1, 1, 64, 64), dtype=tf.float32, name=None)
  1696939865488: TensorSpec(shape=(1, 1, 64, 64), dtype=tf.float32, name=None)
  1696795666448: TensorSpec(shape=(1, 1, 64, 64), dtype=tf.float32, name=None)
  1696939856464: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696939863184: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696795666256: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696939855504: TensorSpec(shape=(3, 3, 256, 64), dtype=tf.float32, name=None)
  1696939866064: TensorSpec(shape=(3, 3, 128, 64), dtype=tf.float32, name=None)
  1696795669712: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1696939862608: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696939860304: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696795659344: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696939858384: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1696939866256: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1696795665680: TensorSpec(shape=(3, 3, 64, 64), dtype=tf.float32, name=None)
  1696939864528: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696939859536: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696795667600: TensorSpec(shape=(64,), dtype=tf.float32, name=None)
  1696939852624: TensorSpec(shape=(1, 1, 64, 24), dtype=tf.float32, name=None)
  1696939867024: TensorSpec(shape=(1, 1, 64, 24), dtype=tf.float32, name=None)
  1696795663376: TensorSpec(shape=(1, 1, 64, 24), dtype=tf.float32, name=None)
  1696939857424: TensorSpec(shape=(1, 1, 16, 1), dtype=tf.float32, name=None)
  1696939851856: TensorSpec(shape=(24,), dtype=tf.float32, name=None)
  1696939862992: TensorSpec(shape=(24,), dtype=tf.float32, name=None)
  1696795663952: TensorSpec(shape=(24,), dtype=tf.float32, name=None)
  1696939855696: TensorSpec(shape=(3,), dtype=tf.int64, name=None)
  1696939859152: TensorSpec(shape=(3,), dtype=tf.int64, name=None)
  1696939852816: TensorSpec(shape=(3,), dtype=tf.int64, name=None)
  1696939864144: TensorSpec(shape=(3,), dtype=tf.int64, name=None)
  1696939861264: TensorSpec(shape=(1, 2, 8400), dtype=tf.float32, name=None)
  1696939852432: TensorSpec(shape=(1, 2, 8400), dtype=tf.float32, name=None)
  1696939855120: TensorSpec(shape=(3,), dtype=tf.int64, name=None)
  1696939858960: TensorSpec(shape=(3,), dtype=tf.int64, name=None)
  1696939858192: TensorSpec(shape=(3,), dtype=tf.int64, name=None)
  1696939854928: TensorSpec(shape=(3,), dtype=tf.int64, name=None)
  1697036584336: TensorSpec(shape=(1500, 4), dtype=tf.int64, name=None)
  1697036584144: TensorSpec(shape=(2,), dtype=tf.int64, name=None)
  1697036583952: TensorSpec(shape=(2,), dtype=tf.int64, name=None)
  1697036585104: TensorSpec(shape=(), dtype=tf.int32, name=None)
  1697036585488: TensorSpec(shape=(), dtype=tf.int32, name=None)
  1697036583184: TensorSpec(shape=(1,), dtype=tf.bool, name=None)
  1697036583568: TensorSpec(shape=(1,), dtype=tf.int32, name=None)
  1697036585680: TensorSpec(shape=(), dtype=tf.int32, name=None)
  1697036583376: TensorSpec(shape=(), dtype=tf.int32, name=None)
  1697036584528: TensorSpec(shape=(), dtype=tf.int32, name=None)
  1697036586064: TensorSpec(shape=(), dtype=tf.float32, name=None)
  1697036582992: TensorSpec(shape=(), dtype=tf.float32, name=None)
  1696939855312: TensorSpec(shape=(3,), dtype=tf.int64, name=None)
  1696939860880: TensorSpec(shape=(3,), dtype=tf.int64, name=None)
  1697036586832: TensorSpec(shape=(2, 2), dtype=tf.int32, name=None)
  1697036585296: TensorSpec(shape=(), dtype=tf.int64, name=None)
  1697036586640: TensorSpec(shape=(), dtype=tf.int64, name=None)
  1697036584720: TensorSpec(shape=(1,), dtype=tf.int64, name=None)
  1697036588176: TensorSpec(shape=(1,), dtype=tf.int64, name=None)
  1697036587984: TensorSpec(shape=(1,), dtype=tf.int64, name=None)
  1697036587600: TensorSpec(shape=(), dtype=tf.int64, name=None)
  1697036587024: TensorSpec(shape=(1,), dtype=tf.int64, name=None)
  1697036589520: TensorSpec(shape=(1,), dtype=tf.int64, name=None)
  1697036588752: TensorSpec(shape=(1,), dtype=tf.int64, name=None)
  1697036591440: TensorSpec(shape=(1, 300, 6), dtype=tf.float32, name=None)
  1697036590288: TensorSpec(shape=(1, 1), dtype=tf.int64, name=None)


TensorFlow SavedModel: export success  576.7s, saved as 'C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\checkpoints\yolov8n_dhakaroadnet_baseline\best_saved_model' (39.3 MB)

TensorFlow Lite: starting export with tensorflow 2.20.0...
TensorFlow Lite: export success  0.0s, saved as 'C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\checkpoints\yolov8n_dhakaroadnet_baseline\best_saved_model\best_int8.tflite' (3.3 MB)

Export complete (577.0s)
Results saved to C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\checkpoints\yolov8n_dhakaroadnet_baseline\best_saved_model\best_int8.tflite
Predict:         yolo predict task=detect model=C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\checkpoints\yolov8n_dhakaroadnet_baseline\best_saved_model\best_int8.tflite imgsz=640 int8
Validate:        yolo val task=detect model=C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\checkpoints\yolov8n_dhakaroadnet_baseline\best_saved_model\best_int8.tflite imgsz=640 data=C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\data\roboflow\data_yolov8.yaml int8
Visualize:       https://netron.app
Finished INT8 TFLite: C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\exported\tflite\dhakaroadnet_yolov8n_int8.tflite (3.18 MB)

{'name': 'INT8 TFLite',
 'status': 'success',
 'path': 'C:\\Users\\USER\\Desktop\\ML\\WorkSpace\\DhakaRoadNet-EdgeAI\\model\\exported\\tflite\\dhakaroadnet_yolov8n_int8.tflite',
 'size_mb': 3.18,
 'half': False,
 'int8': True,
 'nms': True,
 'imgsz': 640,
 'raw_export_result': 'C:\\Users\\USER\\Desktop\\ML\\WorkSpace\\DhakaRoadNet-EdgeAI\\model\\checkpoints\\yolov8n_dhakaroadnet_baseline\\best_saved_model\\best_int8.tflite',
 'error': ''}

## Step 12: Save export summary

This summary makes the notebook useful for documentation, GitHub, and later Android decisions.

In [12]:
export_summary = pd.DataFrame(export_records)
summary_csv_path = REPORT_DIR / "export_summary.csv"
summary_json_path = REPORT_DIR / "export_summary.json"

export_summary.to_csv(summary_csv_path, index=False)
summary_json_path.write_text(json.dumps(export_records, indent=2), encoding="utf-8")

print("Saved CSV summary:", summary_csv_path)
print("Saved JSON summary:", summary_json_path)
export_summary

Saved CSV summary: C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\reports\tflite_export\export_summary.csv
Saved JSON summary: C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\reports\tflite_export\export_summary.json

,name,status,path,size_mb,half,int8,nms,imgsz,raw_export_result,error
0,FP32 TFLite,success,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,11.78,False,False,True,640,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,
1,FP16 TFLite,success,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,11.79,True,False,True,640,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,
2,INT8 TFLite,success,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,3.18,False,True,True,640,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,

## Step 13: Select sample images for prediction checks

A real export is not complete until the exported model is tested visually. This cell selects a few test images from your Roboflow test split.

In [13]:
TEST_IMAGE_DIR = PROJECT_ROOT / "data" / "roboflow" / "test" / "images"
sample_images = sorted(TEST_IMAGE_DIR.glob("*.jpg"))[:5]

print("Sample image directory:", TEST_IMAGE_DIR)
print("Number of selected sample images:", len(sample_images))
for path in sample_images:
    print(path.name)

Sample image directory: C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\data\roboflow\test\images
Number of selected sample images: 5
13_jpg.rf.a83769ea84ab33ba8b24306f38f8a107.jpg
15_jpg.rf.10babafabc168b49e3eec7b7e9459d4e.jpg
1_jpg.rf.35574b68fbec2a2d4e24066ad817cfbb.jpg
20_jpg.rf.bd8db1759b0cd63298d9c75d1253b4dc.jpg
27_jpg.rf.4cca0863ca9530774f72122824824938.jpg

## Step 14: Prediction helper for `.pt` and `.tflite`

This helper saves annotated prediction images. If a TFLite model cannot be loaded by Ultralytics on your machine, the error is saved in the report instead of stopping the notebook.

In [14]:
prediction_records = []


def run_prediction_check(model_path, model_label, images, confidence=0.25):
    print(f"Checking predictions for {model_label}...")
    try:
        check_model = YOLO(str(model_path))
        for image_path in images:
            started_at = time.perf_counter()
            results = check_model.predict(
                source=str(image_path),
                imgsz=IMAGE_SIZE,
                conf=confidence,
                device="cpu",
                verbose=False,
            )
            elapsed_seconds = time.perf_counter() - started_at
            result = results[0]
            annotated_bgr = result.plot()
            annotated_rgb = cv2.cvtColor(annotated_bgr, cv2.COLOR_BGR2RGB)

            output_name = f"{model_label}_{image_path.stem}.jpg".replace(" ", "_").lower()
            output_path = PREDICTION_DIR / output_name
            Image.fromarray(annotated_rgb).save(output_path)

            detection_count = 0 if result.boxes is None else len(result.boxes)
            prediction_records.append(
                {
                    "model_label": model_label,
                    "model_path": str(model_path),
                    "image": image_path.name,
                    "status": "success",
                    "detections": int(detection_count),
                    "time_seconds": round(float(elapsed_seconds), 4),
                    "output_path": str(output_path),
                    "error": "",
                }
            )
        print(f"Finished prediction check for {model_label}.")

    except Exception as exc:
        prediction_records.append(
            {
                "model_label": model_label,
                "model_path": str(model_path),
                "image": "",
                "status": "failed",
                "detections": None,
                "time_seconds": None,
                "output_path": "",
                "error": str(exc),
            }
        )
        print(f"Prediction check failed for {model_label}:", exc)

## Step 15: Run visual prediction checks

This compares the original PyTorch checkpoint with each successful TFLite export.

In [15]:
if sample_images:
    run_prediction_check(MODEL_PATH, "pt_best", sample_images)

    for record in export_records:
        if record["status"] == "success" and record["path"]:
            model_label = record["name"].replace(" TFLite", "").lower()
            run_prediction_check(Path(record["path"]), model_label, sample_images)
else:
    print("No sample images found. Add test images before running prediction checks.")

prediction_summary = pd.DataFrame(prediction_records)
prediction_summary_path = REPORT_DIR / "prediction_check_summary.csv"
prediction_summary.to_csv(prediction_summary_path, index=False)

print("Saved prediction summary:", prediction_summary_path)
prediction_summary

Checking predictions for pt_best...
Finished prediction check for pt_best.
Checking predictions for fp32...
WARNING Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', 'pose', 'obb' or 'semantic'.
Loading C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\exported\tflite\dhakaroadnet_yolov8n_fp32.tflite for TensorFlow Lite inference...
Finished prediction check for fp32.
Checking predictions for fp16...
WARNING Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', 'pose', 'obb' or 'semantic'.
Loading C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\exported\tflite\dhakaroadnet_yolov8n_fp16.tflite for TensorFlow Lite inference...
Finished prediction check for fp16.
Checking predictions for int8...
WARNING Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', 'pose', 'obb' or 'semantic'.
Loading C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\model\exported\tflite\dhakaroadnet_yolov8n_int8.tflite for TensorFlow Lite inference...
Finished prediction check for int8.
Saved prediction summary: C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\reports\tflite_export\prediction_check_summary.csv

,model_label,model_path,image,status,detections,time_seconds,output_path,error
0,pt_best,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,13_jpg.rf.a83769ea84ab33ba8b24306f38f8a107.jpg,success,2,0.1439,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,
1,pt_best,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,15_jpg.rf.10babafabc168b49e3eec7b7e9459d4e.jpg,success,0,0.0954,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,
2,pt_best,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,1_jpg.rf.35574b68fbec2a2d4e24066ad817cfbb.jpg,success,2,0.0962,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,
3,pt_best,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,20_jpg.rf.bd8db1759b0cd63298d9c75d1253b4dc.jpg,success,1,0.0897,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,
4,pt_best,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,27_jpg.rf.4cca0863ca9530774f72122824824938.jpg,success,3,0.1952,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,
5,fp32,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,13_jpg.rf.a83769ea84ab33ba8b24306f38f8a107.jpg,success,2,0.2339,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,
6,fp32,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,15_jpg.rf.10babafabc168b49e3eec7b7e9459d4e.jpg,success,0,0.1412,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,
7,fp32,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,1_jpg.rf.35574b68fbec2a2d4e24066ad817cfbb.jpg,success,2,0.1474,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,
8,fp32,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,20_jpg.rf.bd8db1759b0cd63298d9c75d1253b4dc.jpg,success,1,0.1397,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,
9,fp32,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,27_jpg.rf.4cca0863ca9530774f72122824824938.jpg,success,3,0.1391,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,
10,fp16,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,13_jpg.rf.a83769ea84ab33ba8b24306f38f8a107.jpg,success,2,0.2100,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,
11,fp16,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,15_jpg.rf.10babafabc168b49e3eec7b7e9459d4e.jpg,success,0,0.1508,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,
12,fp16,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,1_jpg.rf.35574b68fbec2a2d4e24066ad817cfbb.jpg,success,2,0.1464,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,
13,fp16,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,20_jpg.rf.bd8db1759b0cd63298d9c75d1253b4dc.jpg,success,1,0.1422,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,
14,fp16,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,27_jpg.rf.4cca0863ca9530774f72122824824938.jpg,success,3,0.1439,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,
15,int8,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,13_jpg.rf.a83769ea84ab33ba8b24306f38f8a107.jpg,success,2,0.1825,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,
16,int8,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,15_jpg.rf.10babafabc168b49e3eec7b7e9459d4e.jpg,success,1,0.1451,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,
17,int8,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,1_jpg.rf.35574b68fbec2a2d4e24066ad817cfbb.jpg,success,300,0.1477,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,
18,int8,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,20_jpg.rf.bd8db1759b0cd63298d9c75d1253b4dc.jpg,success,2,0.1442,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,
19,int8,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,27_jpg.rf.4cca0863ca9530774f72122824824938.jpg,success,300,0.1436,C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNe...,

## Step 16: Write final export report

This markdown report explains what was exported and gives a practical recommendation for Android development.

In [ ]:
successful_exports = [record for record in export_records if record["status"] == "success"]

if any(record["name"] == "FP16 TFLite" and record["status"] == "success" for record in export_records):
    recommendation = "Use FP16 TFLite first in the Android app. Keep FP32 for debugging and test INT8 carefully."
elif any(record["name"] == "FP32 TFLite" and record["status"] == "success" for record in export_records):
    recommendation = "Use FP32 TFLite for initial Android integration, then retry FP16/INT8 export."
else:
    recommendation = "No TFLite export succeeded. Fix dependency/export errors before Android integration."

report_path = REPORT_DIR / "export_summary.md"
report_text = f"""# DhakaRoadNet TFLite Export Summary

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Source Model

- Model: `{MODEL_PATH}`
- Dataset YAML: `{DATA_YAML_PATH}`
- Image size: `{IMAGE_SIZE}`
- NMS included in export: `{USE_NMS}`

## Exported Files

{export_summary.to_markdown(index=False) if not export_summary.empty else 'No export records found.'}

## Android Files

- TFLite models: `{EXPORT_DIR}`
- Labels file: `{labels_path}`
"""

report_path.write_text(report_text, encoding="utf-8")
print("Saved markdown report:", report_path)
print(recommendation)

Saved markdown report: C:\Users\USER\Desktop\ML\WorkSpace\DhakaRoadNet-EdgeAI\reports\tflite_export\export_summary.md
Use FP16 TFLite first in the Android app. Keep FP32 for debugging and test INT8 carefully.